### ISSUE TITLE
Ideia: ter um documento com indicações para a padronização da tradução

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/dados#59]
- Não colocar ponto final nos textos de `desc` . 

- Não utilizar acentuação e espaços em `trans`, pois é a tradução do nome das variáveis. 

- Utilizar fator em vez de factor.

- Os campos mostrados no exemplo abaixo são correspondentes ao nome da base. Usar igual, não colocar espaços e acentos.

```
df: 
   name: ... 

```
```
help:
  name: ..
  alias: ..
  usage: ...
```

**Comment by rivaquiroga** [comment]
¡Buena idea!
Puse lo que escribiste en la página de Wiki del repositorio: https://github.com/cienciadedatos/dados/wiki/Indica%C3%A7%C3%B5es-para-a-padroniza%C3%A7%C3%A3o-da-tradu%C3%A7%C3%A3o

**Comment by beatrizmilz** [comment]
Gracias Riva!! Voy a cerrar este issue entonces :)
