### ISSUE TITLE
AmesHousing::ames_raw

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/dados#68]
Precisamos resolver o que fazer sobre esse caso, escrito por @rivaquiroga :

 @williamorim @beatrizmilz 

I just realized that in many cases you made the translated values extreamly long. I'm not sure if this is always useful. If you plot this variables you'll have to edit the way the values appear in the axes. And if your screen is small you can't see the complete values in the Console. Maybe is a better idea to keep the values short (for example,  `boa` instead of `boa (lareira de alvenaria no nível principal)`), and include a link to a translated version of the data documentation.

![Rplot01](https://user-images.githubusercontent.com/31421616/94627508-268b2280-0294-11eb-9683-fdb40b135072.png)

![Captura de pantalla de 2020-09-29 20-44-03](https://user-images.githubusercontent.com/31421616/94627673-90a3c780-0294-11eb-9501-8df3874d0845.png)

_Originally posted by @rivaquiroga in https://github.com/cienciadedatos/dados/pull/67#discussion_r497151564_

**Comment by beatrizmilz** [comment]
Minha sugestão:


Or we can add this translation to the description of the variable, to appear in the documentation. Ex:

```
lareira_qualidade
Qualidade da(s) lareira(s). Categorias: excelente (fogueira de alvenaria excepcional); boa (lareira de alvenaria no nível principal),  média (lareira pré-fabricada na sala de estar principal ou lareira de alvenaria no porão),  regular (fogueira pré-fabricada no porão), ruim (fogão Ben Franklin).
```

What do you think @rivaquiroga and @williamorim ?

_Originally posted by @beatrizmilz in https://github.com/cienciadedatos/dados/pull/67#discussion_r497444749_

**Comment by williamorim** [comment]
As statistician, I always vote for "information is gold". The extremely long values are really annoying, but I've tried to put all extra information inside parentheses. So all extra information can be removed using

``` r
base <- dplyr::mutate(
  dados::ames, 
  dplyr::across(.fns = ~ stringr::str_remove(.x, " [(].*[)]"))
)

unique(base$lareira_qualidade)
#> [1] "boa"       NA          "média"     "ruim"      "excelente" "regular"
```

<sup>Created on 2020-10-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But I admit it is a matter of preference. I prefer to have the information within the data (since I can easily remove it). One could prefer to have it detached of the data.

**Comment by rivaquiroga** [comment]
Closed via https://github.com/cienciadedatos/dados/pull/69
