### ISSUE TITLE
Submit to CRAN

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/dados#74]
@rivaquiroga now that we accepted all translations, do you think we can start thinking about submitting to CRAN?

Thanks!

**Comment by rivaquiroga** [comment]
@beatrizmilz, if you don't want to add more datasets and you are sure that there is no need to fix the translations that are already in the package, then yes!

**Comment by beatrizmilz** [comment]
I think the only thing to think about in the future is the lists inside starwars dataset. But for now I don't know how to implement it. Also there is no more datasets planned to be translated, so I think we are good to go! @rivaquiroga what do you think?
