### ISSUE TITLE
 Translate dataset stringr::fruit - used in the regexps chapter from R4DS

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/dados#89]

**Comment by rivaquiroga** [comment]
Olá!! The datasets from the stringr package (fruit, words, sentences) can't be translated as we did with the other ones, because these are not dataframes. In this case we created them like this: https://github.com/cienciadedatos/datos/blob/main/data-raw/frutas.R

**Comment by scopinho** [comment]
> @scopinho Olá! eu to atrasada no acompanhamento pq tá corrido no trabalho, mas vi que você está trabalhando nos capítulos de regex que usam esses dados!

Oi @beatrizmilz , imagina, sem problemas. Sim, acabei deixando os exemplos em inglês por ora, pois os casos de regex teremos que ser bem criativos pra achar nomes em.PT que coincidam com os em inglês, principalmente com duas consoantes, etc...mas depois de traduzidos posso ver como fica. o de frutas eu coloquei um lista inicial no comentário do regex se quiser usar/comparar.

**Comment by beatrizmilz** [comment]
> Olá!! The datasets from the stringr package (fruit, words, sentences) can't be translated as we did with the other ones, because these are not dataframes. In this case we created them like this: https://github.com/cienciadedatos/datos/blob/main/data-raw/frutas.R

Thank you Riva!
I created a PR inspired on the code you showed: https://github.com/cienciadedatos/dados/pull/108
