### ISSUE TITLE
Translate dataset stringr::words - used in the regexps chapter from R4DS

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/dados#90]

**Comment by rivaquiroga** [comment]
:eyes: https://github.com/cienciadedatos/dados/issues/89#issuecomment-1811513862

For the Spanish version we didn't translate the words. We used a frequency list of Spanish words from the Royal Academy of the Spanish Language, and we adapted the examples. A similar list for Portuguese should be available somewhere.
